import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Providers from "../components/providers";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Team Chat Application",
    description: "Generated by Team Chat Application",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body
                    className={
                        (cn(font.className), "bg-white dark:bg-[#313338]")
                    }
                >
                    <Providers>{children}</Providers>
                </body>
            </html>
        </ClerkProvider>
    );
}
